services:
  # EMQX Broker 1
  emqx1:
    image: emqx/emqx:5.7.1
    hostname: emqx1
    container_name: emqx1
    restart: unless-stopped
    environment:
      - EMQX_NAME=emqx1
      - EMQX_NODE__NAME=emqx1@emqx1
      - EMQX_CLUSTER__DISCOVERY=static
      - EMQX_CLUSTER__STATIC__SEEDS=emqx1@emqx1,emqx2@emqx2,emqx3@emqx3
    ports:
      - "1883:1883" # MQTT TCP
      - "18083:18083" # Dashboard HTTP
      - "8083:8083" # WebSocket MQTT
    networks:
      - mqtt-cluster

  # EMQX Broker 2
  emqx2:
    image: emqx/emqx:5.7.1
    hostname: emqx2
    container_name: emqx2
    restart: unless-stopped
    environment:
      - EMQX_NAME=emqx2
      - EMQX_NODE__NAME=emqx2@emqx2
      - EMQX_CLUSTER__DISCOVERY=static
      - EMQX_CLUSTER__STATIC__SEEDS=emqx1@emqx1,emqx2@emqx2,emqx3@emqx3
    ports:
      - "1884:1883"
      - "18084:18083" # Dashboard HTTP
      - "8084:8083" # WebSocket MQTT
    networks:
      - mqtt-cluster

  # EMQX Broker 3
  emqx3:
    image: emqx/emqx:5.7.1
    hostname: emqx3
    container_name: emqx3
    restart: unless-stopped
    environment:
      - EMQX_NAME=emqx3
      - EMQX_NODE__NAME=emqx3@emqx3
      - EMQX_CLUSTER__DISCOVERY=static
      - EMQX_CLUSTER__STATIC__SEEDS=emqx1@emqx1,emqx2@emqx2,emqx3@emqx3
    ports:
      - "1885:1883"
      - "18085:18083" # Dashboard HTTP
      - "8085:8083" # WebSocket MQTT
    networks:
      - mqtt-cluster

  # HAProxy Load Balancer
  haproxy:
    image: haproxy:2.4
    hostname: haproxy
    container_name: mqtt-haproxy
    restart: unless-stopped
    ports:
      - "1880:1883" # Main MQTT entrypoint for simulator
      - "8080:8080" # HAProxy stats page
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - emqx1
      - emqx2
      - emqx3
    networks:
      - mqtt-cluster

networks:
  mqtt-cluster:
    driver: bridge
