// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251019195407_SeparateTemperatureAndNoiseTables")]
    partial class SeparateTemperatureAndNoiseTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("backend.Models.CarriageNoise", b =>
                {
                    b.Property<int>("CarriageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("NoiseLevel")
                        .HasColumnType("REAL");

                    b.HasKey("CarriageId", "Date");

                    b.ToTable("CarriageNoises");
                });

            modelBuilder.Entity("backend.Models.CarriageNoiseAndTemp", b =>
                {
                    b.Property<int>("CarriageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<float>("NoiseLevel")
                        .HasColumnType("REAL");

                    b.Property<float>("Temperature")
                        .HasColumnType("REAL");

                    b.HasKey("CarriageId", "Date");

                    b.ToTable("CarriageNoiseAndTemps");
                });

            modelBuilder.Entity("backend.Models.CarriageSeats", b =>
                {
                    b.Property<int>("CarriageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("OcupiedSeats")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OcupiedSeatsBitMap")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("INTEGER");

                    b.HasKey("CarriageId", "Date");

                    b.ToTable("CarriageSeats");
                });

            modelBuilder.Entity("backend.Models.CarriageTemperature", b =>
                {
                    b.Property<int>("CarriageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<float>("Humidity")
                        .HasColumnType("REAL");

                    b.Property<string>("SensorLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Temperature")
                        .HasColumnType("REAL");

                    b.HasKey("CarriageId", "Date");

                    b.ToTable("CarriageTemperatures");
                });
#pragma warning restore 612, 618
        }
    }
}
